"""empty message

Revision ID: d3dead12224b
Revises: 
Create Date: 2025-07-10 14:02:25.409083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3dead12224b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('roles',
               existing_type=postgresql.ENUM('manager', 'developer', 'admin', name='roles_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('roles',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('manager', 'developer', 'admin', name='roles_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###
